syntax = "proto3";

package wellness.gym;

option java_multiple_files = true;
option java_package = "edu.eci.arsw.wellness.proto.gym";

service GymService {
    rpc ReserveGymSession (GymReservationRequest) returns (GymReservationResponse);
    rpc CancelGymReservation (CancelGymRequest) returns (CancelGymResponse);
    rpc GetStudentReservations (StudentGymRequest) returns (GymReservationList);
    rpc GetAvailableSessions (EmptyGymRequest) returns (AvailableSessionsResponse);
}

message EmptyGymRequest {}

message GymReservationRequest {
    string student_id = 1;
    string student_name = 2;
    string time_slot = 3;
    string session_type = 4;
}

message GymReservationResponse {
    bool success = 1;
    string reservation_id = 2;
    string message = 3;
    string confirmed_slot = 4;
}

message CancelGymRequest {
    string reservation_id = 1;
    string student_id = 2;
}

message CancelGymResponse {
    bool success = 1;
    string message = 2;
}

message StudentGymRequest {
    string student_id = 1;
}

message GymReservationInfo {
    string id = 1;
    string student_id = 2;
    string student_name = 3;
    string time_slot = 4;
    string session_type = 5;
    string status = 6;
}

message GymReservationList {
    repeated GymReservationInfo reservations = 1;
}

message AvailableSessionsResponse {
    repeated string available_slots = 1;
    map<string, int32> session_capacity = 2;
}